Algoritmo "d02"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis 
   nome: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Qual é o seu nome?: ")
   Leia(nome)
   Escreva("Olá ", nome, ", é um prazer te conhecer!")

Fimalgoritmo