Algoritmo "d003"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis 
   nome: caractere
   salario: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Nome do Funcionário(a): ")
   Leia(nome)
   Escreva("Salário: ")
   Leia(salario)
   Escreva("O(A) Funcionário(a) ", nome, " tem um salário de R$",salario, " em Junho." )

Fimalgoritmo