Algoritmo "d005"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis 
   nota1, nota2: real
   media: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Nota 1: ")
   Leia(nota1)
   Escreva("Nota 2: ")
   Leia(nota2)
   media <- (nota1 + nota2) / 2
   Escreva("A média entre", nota1, " e", nota2, " é igual a", media)

Fimalgoritmo