Algoritmo "d006"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis 
   num, ant, suc: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Digite um número: ")
   Leia(num)
   ant <- num - 1
   Escreval("O antecessor de", num, " é", ant)
   suc <- num + 1
   Escreva("O sucessor de", num, " é", suc)

Fimalgoritmo