Algoritmo "d009"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis 
   ctr: real
   dol: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval("Quanto dinheiro você tem em R$ na carteira?: ")
   Leia(ctr)
   dol <- ctr / 5.27
   Escreva("Você pode comprar", dol, "US$")
   
Fimalgoritmo