Algoritmo "combinacoes"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/04/2026
Var
// Seção de Declarações das variáveis 
   c1, c2: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Para c1 := 1 ate 3 faca
      Para c2 := 1 ate 3 faca
         Escreval (c1, c2)
      FimPara
   FimPara

Fimalgoritmo