Algoritmo "conversor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis 
   angulo, seno: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Informe um angulo: ")
   Leia(angulo)
   seno <- Sen(GraupRad(angulo))
   Escreva("O seno de", angulo," e igual a", seno)

Fimalgoritmo