Algoritmo "creuza01"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/04/2026
Var
// Seção de Declarações das variáveis 
   ano_atual, ano_nasc, idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Em que ano nós estamos?: ")
   Leia(ano_atual)
   Escreva("Em que ano eu nasci?: ")
   Leia(ano_nasc)
   idade <- ano_atual - ano_nasc
   Escreva("Minha idade será:", idade)

Fimalgoritmo