Algoritmo "fazsomaprocedimento"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/04/2026
Var
// Seção de Declarações das variáveis 
   x, y: inteiro
   
Procedimento soma(a, b: inteiro)
inicio
   Escreval ("Recebi o valor", a)
   Escreval ("Recebi o valor", b)
   Escreva ("A soma entre os dois é", a + b)
FimProcedimento

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   x <- 5
   y <- 3
   soma(x, y)

Fimalgoritmo