Algoritmo "somador"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/04/2026
Var
// Seção de Declarações das variáveis 
   n, c, s: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   s <- 0
   Para c <- 1 ate 5 faca
      Escreval ("Digite um número: ")
      Leia (n)
      s <- s + n
   FimPara
   Escreva ("A soma dos valores é", s)

Fimalgoritmo